suport matches operator
infobloxopen/seal pull request #100
Opened 2020-10-27 14:35 UTC by abynenkov-ib

2020-10-27 19:38 UTC, rchowinfoblox commented
Alexey you're gonna hate this, but I realized I recalled the wrong token for regexp operator in perl: it's `=~` (and `!~`), not `~=`.
If it's possible I think we should change to `=~` as that's what most people are used to.  And should we also support `!~` for negated regexp matching?

2020-10-27 23:05 UTC, wplu commented
yes, please change it - i have changed the desc in the issue

2020-10-27 23:06 UTC, wplu commented
we'll support !~ in a different issue

2020-10-28 10:00 UTC, abynenkov-ib commented
Done, but `~=` seems better to me
And I agree with Phil, `!~` (not match) is not needed, because it's possible to use `not` operator in seal

2020-10-28 15:04 UTC, wplu commented on docs/source/examples/petstore/petstore.all.seal
> +deny subject group regexp to use petstore.* where subject.iss =~ ".*regexp.*";
```suggestion
deny subject group everyone to use petstore.* where where subject.jti =~ "@petstore.swagger.io$";
```

2020-10-28 15:06 UTC, wplu commented on docs/source/examples/petstore/petstore.all.test.rego
> +			"iss": "just test regexp params",
please use `jti` as in example from petstore.all.seal

2020-10-28 15:06 UTC, wplu commented on docs/source/examples/petstore/petstore.all.test.rego
> +			"iss": "iss should not match",
please use jti as in example from petstore.all.seal

2020-10-28 15:12 UTC, wplu requested changes
please change example in petstore.all.seal - otherwise LGTM!

2020-10-28 15:25 UTC, abynenkov-ib commented on docs/source/examples/petstore/petstore.all.seal
> +deny subject group regexp to use petstore.* where subject.iss =~ ".*regexp.*";
done

2020-10-28 15:49 UTC, wplu approved these changes

2020-10-28 15:49 UTC, merged